name: "Close stale pull requests"
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          stale-pr-message: |
            **tl;dr** our action detected no activity on this PR and will close it in 30 days if the stale label is not removed.

            We welcomes your contribution! It means a lot to us.

            This PR has not seen any activity in the last 30 days. That is why we wanted to check whether you are still working on it or need assistance.
            Please note that this is an automated message and we might very well be the reason why there has not been any activity lately. We certainly do not want to discourage you from contributing. We do need to be honest in that we have limited resources for reviewing PRs.

            If you do not have time to continue the work or have moved on you don’t need to do anything. We will automatically close the PR in 7 days. We hope to see you back soon :)
            If you would like to continue working on it or require help from us please remove the stale label and respond by commenting on the issue.
          close-pr-message: |
            **tl;dr** closing this PR since it has not seen any activity in the last 30 days.

            We welcomes your contribution! It means a lot to us. We certainly do not want to discourage you from contributing. We do need to be honest in that we have limited resources for reviewing PRs. Your PR has not seen any activity in the last 30 days. This is why we have decided to close this PR for now. This allows us to focus our limited time to review all other PRs in a timely and professional manner.

            Thank you very much for your help and understanding :)
